spring:
  security:
    user:
      name: user
      password: pass
  application:
    name: Task Intelligence Api

  datasource:
    url: jdbc:postgresql://localhost:5432/TaskIntelligenceApiDB
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true