spring:
  application:
    name: Task Intelligence Api

  datasource:
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    show-sql: false

  threads:
    virtual:
      enabled: true
jwt:
  secret: moj-super-tajny-klucz-minimum-32-znaki