spring:
  application:
    name: Task Intelligence Api

  datasource:
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc.hibernate.jdbc.batch_size: 50
        order_updates: true

  threads:
    virtual:
      enabled: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest


jwt:
  secret: moj-super-tajny-klucz-minimum-32-znaki

